'use strict';

const { contextBridge, ipcRenderer } = require('electron');

// Only the browser's own browser:// pages (toolbar UI + internal pages) get the API.
// The main process re-checks the sender on every call, so websites never reach it.
if (location.protocol === 'browser:' && window === window.top) {
  const call = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);
  const on = (channel) => (cb) => ipcRenderer.on(channel, (_e, payload) => cb(payload));

  contextBridge.exposeInMainWorld('browserAPI', {
    newTab: call('tab:new'),
    closeTab: call('tab:close'),
    selectTab: call('tab:select'),
    tabMenu: call('tab:menu'),
    setOverlay: call('ui:overlay'),
    historyMenu: call('nav:history-menu'),
    resetZoom: call('zoom:reset'),
    stopCapture: call('capture:stop'),
    goHome: call('nav:home'),
    focusPage: call('focus:page'),
    restorePages: call('restore:accept'),
    dismissRestore: call('restore:dismiss'),
    currentPagesForStartup: call('startup:current-pages'),
    chooseDownloadFolder: call('downloads:choose-folder'),
    removeHistoryEntry: call('data:history-remove'),
    suggest: call('suggest'),
    siteInfo: call('site:info'),
    setSitePermission: call('site:set-permission'),
    clearSiteData: call('site:clear-data'),
    moveTab: call('tab:move'),
    muteTab: call('tab:mute'),
    go: call('nav:go'),
    back: call('nav:back'),
    forward: call('nav:forward'),
    reload: call('nav:reload'),
    toggleBookmark: call('bookmark:toggle'),
    respondPermission: call('permission:respond'),
    getPermissions: call('data:permissions'),
    resetPermissions: call('data:permission-reset'),
    setSitePermissionFromSettings: call('data:permission-set'),
    getPermissionDefaults: call('data:permission-defaults'),
    setPermissionDefault: call('data:permission-default-set'),
    relaunch: call('app:relaunch'),
    getHistory: call('data:history'),
    clearBrowsingData: call('data:clear-browsing'),
    clearHistory: call('data:history-clear'),
    getBookmarks: call('data:bookmarks'),
    removeBookmark: call('data:bookmark-remove'),
    find: call('find:query'),
    closeFind: call('find:close'),
    openDownloads: call('downloads:open'),
    installUpdate: call('update:install'),
    getAbout: call('about:info'),
    checkForUpdates: call('about:check'),
    installUpdateFromSettings: call('about:install'),
    respondAuth: call('auth:respond'),
    toggleSiteBlocking: call('adblock:toggle-site'),
    removeAdblockException: call('data:adblock-allow-remove'),
    getSettings: call('data:settings'),
    setSetting: call('data:settings-set'),
    getDownloads: call('data:downloads'),
    openDownload: call('download:open'),
    showDownload: call('download:show'),
    cancelDownload: call('download:cancel'),
    pauseDownload: call('download:pause'),
    clearDownloads: call('download:clear'),
    decideDownload: call('download:decide'),
    decideDownloadWarning: call('download:warning-decide'),
    onTabs: on('tabs:update'),
    onFocusAddress: on('focus-address'),
    onFocusFind: on('focus-find'),
    onFocusAuth: on('focus-auth'),
    onScreenPicker: on('screen-picker'),
    onStatus: on('status'),
    onBookmarkEdit: on('bookmark-edit'),
    starPage: call('bm:star'),
    openBookmark: call('bm:open'),
    bookmarkFolderMenu: call('bm:folder-menu'),
    bookmarkContextMenu: call('bm:context'),
    bookmarkEditInfo: call('bm:edit-info'),
    updateBookmark: call('bm:update'),
    moveBookmark: call('bm:move'),
    removeBookmarkNode: call('bm:remove'),
    getBookmarkTree: call('bm:tree'),
    addBookmarkFolder: call('bm:add-folder'),
    bookmarkImportSources: call('bm:import-sources'),
    importBookmarks: call('bm:import'),
    exportBookmarks: call('bm:export'),
    onDownloadStarted: on('download-started'),
    recentDownloads: call('downloads:recent'),
    downloadAction: call('downloads:action'),
    chooseScreen: call('screen:choose'),
    getDefaultBrowser: call('default:status'),
    setDefaultBrowser: call('default:set'),
  });
}
