# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Ezzeddin.Operecs
PackageVersion: 0.22.3
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ezzeldinzozz-svg/operecs-browser/releases/download/v0.22.3/Operecs-Setup-0.22.3.exe
    InstallerSha256: 205023C825D12ACFEA3DEF60145CE6C5D2B90622BF28F7045C8979987ACFDB9B
ManifestType: installer
ManifestVersion: 1.6.0
